#!/usr/bin/env ruby

require 'optparse'
require_relative 'lib/config'

opts = {}

OptionParser.new do |op|
  op.on('-e', '--env', 'Get config from env vars') do
    puts 'Reading config from environment variables'
    @mwcfg = MiddlewareConfig.from_env_vars(ENV)
  end

  op.on('-f', '--config-file[=CONFIG_FILE]', 'Read config from file') do |cfg|
    puts "Reading config from file #{cfg}"
    @mwcfg = MiddlewareConfig.from_yaml_file(cfg)
  end

  op.on_tail('-h', '--help') do
    puts op
    exit
  end
end.parse!

output_dir = ARGV[0]
@mwcfg.render(output_dir)
